### ISSUE TITLE
Define structure for static layers in scenarios

### ISSUE THREAD

**Issue by nesnoj** [openego/egon-webapp#17]
- 1 geopackage per aggregation level: MVGD, districts
- Data per layer and scenario as CSV including popup data (first step: add some dummy data #18)
- JSON with layer config: aggregation level, unit, name, info text, popup captions

Related issue in eGon-data: https://github.com/openego/eGon-data/issues/447

**Comment by nesnoj** [comment]
Draft see https://wolke.rl-institut.de/f/371397

**Comment by finnus** [comment]
We tried this approach, but we just have to many models with very little different geoms (mainly mv_grid_district (21 times x 2 scenarios = 42 models). 
This brought me to the conclusion, that it might be easier and less redundant to put the data into one data-model (MVGridDistrictData) and to add a config model (MapLayer), that contains the meta-information to be able to display the data.

That would also reduce the number of files that need to be imported to the number of different geoms, and would make it easy to use the DB instead of json-files for configuration (which is - IMHO - more django-like).

I currently test that out on https://github.com/rl-institut-private/egon_website/tree/fat_model_approach

**Comment by finnus** [comment]
With commit 8731e0620b6615a70f942af06a87ce7751b37d26 the above mentioned solution has been implemented.
